services:
  backend:
    build:
      context: ./backend
    container_name: rmbg_backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: rmbg_frontend
    ports:
      - "3000:3000"
    command: pnpm dev
